package templates

const ClientTpl = `// Code generated by protoc-gen-ekto. DO NOT EDIT.
// source: {{ .InputPath }}
package {{ package . }}

import (
	"context"

	"google.golang.org/grpc"
)
{{ "" }}
{{- range .Services }}
{{- if hasServiceName . }}
{{ template "service" . }}
{{- end }}
{{- end }}
`
