package templates

const DbTpl = `// Code generated by protoc-gen-ekto. DO NOT EDIT.
// source: {{ .InputPath }}
package {{ package . }}

import (
	"github.com/ekto-dev/ekto/db/pkg/database"
)
{{ "" }}
{{- range .Services }}
{{- if hasDatabase . }}
{{ template "connect" . }}
{{- end }}
{{- end }}
`
