package templates

const MqTpl = `// Code generated by protoc-gen-ekto. DO NOT EDIT.
// source: {{ .InputPath }}
package {{ package . }}

import (
	"context"
	"log"
	"net"

	"github.com/ekto-dev/ekto/mq/pkg/cloudevents"
	format "github.com/cloudevents/sdk-go/binding/format/protobuf/v2"
	cloudeventsv2 "github.com/cloudevents/sdk-go/v2"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

var ektoPort = ":3070"
{{ "" }}
{{- range .Services }}
{{ template "service" . }}
{{- end }}
`
