package templates

const ServerTpl = `// Code generated by protoc-gen-ekto. DO NOT EDIT.
// source: {{ .InputPath }}
package {{ package . }}

import (
	ektoserver "github.com/ekto-dev/ekto/server"
	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"golang.org/x/sync/errgroup"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/encoding/protojson"
)
{{ "" }}
{{- range .Services }}
{{ template "service" . }}
{{- end }}
`
